tasks:
  analyze_github_repositories:
    description: |
      Analyze GitHub repositories and extract comprehensive information:
      1. Project overview and description
      2. Technical stack and dependencies
      3. Code quality metrics
      4. Contribution statistics
      5. Project structure
      6. Documentation quality
      7. Development activity
    agent: github_analyst
    expected_output: |
      A detailed analysis of each repository including:
      - Project metadata
      - Technical details
      - Quality metrics
      - Contribution data
    dependencies: []

  evaluate_projects:
    description: |
      Evaluate projects using the STAR method and professional standards:
      1. Situation and Task analysis
      2. Action taken
      3. Results achieved
      4. Technical complexity assessment
      5. Impact evaluation
      6. Areas for improvement
      7. Professional relevance
    agent: project_evaluator
    expected_output: |
      A comprehensive evaluation of each project including:
      - STAR analysis
      - Complexity score
      - Impact assessment
      - Improvement recommendations
    dependencies: [analyze_github_repositories]

  select_best_projects:
    description: |
      Select the most relevant projects based on:
      1. Topic relevance
      2. User preferences
      3. Project quality
      4. Market demand
      5. Career alignment
    agent: project_selector
    expected_output: |
      A list of selected projects with:
      - Selection criteria
      - Relevance scores
      - Justification
    dependencies: [evaluate_projects]

  recommend_learning_path:
    description: |
      Recommend learning resources based on:
      1. Current skills
      2. Target job requirements
      3. Market trends
      4. Career goals
      5. Time constraints
    agent: learning_recommender
    expected_output: |
      A personalized learning plan including:
      - Recommended technologies
      - Course suggestions
      - Certification paths
      - Timeline
    dependencies: [evaluate_projects]

  recommend_new_projects:
    description: |
      Recommend new projects based on:
      1. Career goals
      2. Current skills
      3. Market demand
      4. Learning objectives
      5. Time availability
    agent: project_recommender
    expected_output: |
      A list of recommended projects with:
      - Project descriptions
      - Required skills
      - Learning objectives
      - Implementation steps
      - Resources
    dependencies: [evaluate_projects]

  generate_cv:
    description: |
      Generate a professional CV in markdown format including:
      1. Professional summary
      2. Technical skills
      3. Project experience (STAR method)
      4. Education
      5. Certifications
      6. Additional skills
    agent: cv_generator
    expected_output: |
      A well-formatted CV in markdown with:
      - Clear structure
      - Professional formatting
      - ATS optimization
      - Achievement highlights
    dependencies: [select_best_projects, recommend_learning_path]

  optimize_portfolio:
    description: |
      Optimize the project portfolio by:
      1. Balancing project types
      2. Ensuring skill coverage
      3. Highlighting achievements
      4. Demonstrating progression
      5. Meeting job requirements
    agent: project_selector
    expected_output: |
      An optimized portfolio with:
      - Project selection rationale
      - Skill coverage analysis
      - Career progression path
    dependencies: [select_best_projects, recommend_new_projects] 