analyze_projects:
  description: |
    Analysez les repositories GitHub fournis et évaluez leur qualité technique.
    Utilisez le GitHubAnalyzerTool pour récupérer et analyser les données.
    Sauvegardez les résultats dans le fichier de sortie spécifié.
  expected_output: |
    Un fichier JSON contenant l'analyse détaillée de chaque projet avec:
    - Scores techniques
    - Évaluation des fonctionnalités
    - Technologies utilisées
    - Niveau de difficulté
    - Recommandations d'amélioration

select_best_projects:
  description: |
    Sélectionnez les projets les plus pertinents pour le CV en fonction du poste visé.
    Analysez la correspondance entre les projets et la description du poste.
  expected_output: |
    Un fichier JSON contenant:
    - Liste des projets sélectionnés
    - Justification de la sélection
    - Score de pertinence pour chaque projet

provide_recommendations:
  description: |
    Proposez des recommandations de formation basées sur l'analyse des projets
    et les exigences du poste visé.
  expected_output: |
    Un fichier JSON contenant:
    - Liste des formations recommandées
    - Justification des recommandations
    - Priorités d'apprentissage

generate_cv:
  description: |
    Générez un CV technique optimisé en format Markdown en utilisant
    les projets sélectionnés et les recommandations.
  expected_output: |
    Un fichier Markdown contenant:
    - Informations personnelles
    - Résumé des compétences
    - Projets pertinents
    - Formations recommandées
